import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../lang/i18n"
import "../lang/localeYup"
import "./globals.css"
import { PropsWithChildren } from "react"
import TanstackProvider from "@src/providers/TantaskProvider"
import Navbar from "./ui/navbar"
import { SessionProvider, getSession } from "next-auth/react"
import { BASE_PATH } from "@src/constants/enviroments"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = (props: PropsWithChildren) => {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={`favicon.ico`} />
      </head>
      <body
        className={`${inter.className} bg-gray-200 text-black w-100 h-screen `}
      >
        <Navbar />
        <div className="max-w-7xl mx-auto sm:px-6">{props.children}</div>
      </body>
    </html>
  )
}

export default RootLayout
